name: Develop CI

on:
  push:
    branches: [ "develop" ]
    paths-ignore:
      - "*.md"
  pull_request:
    branches: [ "develop" ]
    paths-ignore:
      - "*.md"

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-
      - name: Install and Build
        run: |
          npm vi
          npm run build-dev

